service: serverless-exchange-alan-zambrano # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
      BUY_ORDERS: ${self.service}-buyorders-${self.provider.stage}
      SELL_ORDERS: ${self.service}-sellorders-${self.provider.stage}
      TRANSACTION: ${self.service}-transactions-${self.provider.stage}

functions:
  ComparadorBuy:
    handler: comparadorbuy.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - buyOrdersTable
              - StreamArn

resources:
  Resources:
      buyOrdersTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self.service}-buyorders-${self.provider.stage}
          AttributeDefinitions:
            - AttributeName: exchange
              AttributeType: S
            - AttributeName: price
              AttributeType: N
          KeySchema:
            - AttributeName: exchange
              KeyType: HASH
            - AttributeName: price
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          StreamSpecification:
            StreamViewType: NEW_AND_OLD_IMAGES
      # sellOrdersTable:
      #   Type: AWS::DynamoDB::Table
      #   Properties:
      #     TableName: ${self.service}-sellorders-${self.provider.stage}
      #     AttributeDefinitions:
      #       - AttributeName: exchange
      #         AttributeType: S
      #       - AttributeName: price
      #         AttributeType: I
      #     KeySchema:
      #       - AttributeName: price
      #         KeyType: HASH
      #       - AttributeName: price
      #         KeyType: RANGE
      #     ProvisionedThroughput:
      #       ReadCapacityUnits: 1
      #       WriteCapacityUnits: 1
      #     StreamSpecification:
      #       StreamViewType: NEW_AND_OLD_IMAGES
      # transactionTable:
      #   Type: AWS::DynamoDB::Table
      #   Properties:
      #     TableName: ${self.service}-transactions-${self.provider.stage}
      #     AttributeDefinitions:
      #       - AttributeName: exchange
      #         AttributeType: S
      #       - AttributeName: price
      #         AttributeType: I
      #     KeySchema:
      #       - AttributeName: price
      #         KeyType: HASH
      #       - AttributeName: price
      #         KeyType: RANGE
      #     ProvisionedThroughput:
      #       ReadCapacityUnits: 1
      #       WriteCapacityUnits: 1
      #     StreamSpecification:
      #       StreamViewType: NEW_AND_OLD_IMAGES
